server:
    port: ${PORT:${SERVER_PORT:0}}

eureka:
    instance:
        hostname: localhost
        instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    client:
        service-url:
            default-zone: http://localhost:8761/

info:
    app:
        name: Gestor de Jugadores
        description: In Charge of Players, CRUD operations on top of MongoDB with Feign capabilities
        version: 3.0
        Development State: Works perfect! ready to connect woth front-end
        Main Features: Spring Boot Data rest, MongoDB, Feign, Swagger to document and explore the API
        Inicio API: http://localhost:${PORT:${SERVER_PORT:0}}/players
        Swagger: http://localhost:${SERVER_PORT:0}/swagger-ui.html
        TODO: Clean Code