server:
    port: ${PORT:${SERVER_PORT:0}}

eureka:
    instance:
        hostname: localhost
        instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    client:
        service-url:
            default-zone: http://localhost:8761/

info:
    app:
        name: Gestor de Juegos
        description: In Charge of Game Repo, CRUD operations on top of MongoDB
        version: 3.0.0
        Development State: Works Flawlessly with the requered functionality
        Main Features: Spring Boot Data rest, MongoDB, Swagger to document and explore the API
        TODO: Use a Final Database, not just a test database without password.
        Inicio API: http://localhost:${PORT:${SERVER_PORT:0}}/games
        Swagger: http://localhost:${SERVER_PORT:0}/swagger-ui.html