server:
    port: ${PORT:${SERVER_PORT:0}}

eureka:
    instance:
        hostname: localhost
        instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    client:
        service-url:
            default-zone: http://localhost:8761/

info:
    app:
        name: Follows and Un-Follows players
        description: Asigns a Follower (Needs an ObjectId) to a Player (ObjectID) in the database micro_services, and un-Follows too
        version: 2.0
        Development State: Working perfectly
        Main Features: Spring Boot Data rest, MongoDB, Swagger to document and explore the API
        Inicio API: http://localhost:${PORT:${SERVER_PORT:0}}/
        Example: POST http://localhost:${SERVER_PORT:0}/player/{player_id}/follower/{follower_id}
        Example Unfollow: DELETE http://localhost:${SERVER_PORT:0}/player/{player_id}/follower/{follower_id}
        Swagger: http://localhost:${SERVER_PORT:0}/swagger-ui.html
        TODO: Nothing