server:
    port: 5930

eureka:
    instance:
        hostname: localhost
        instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    client:
        service-url:
            default-zone: http://localhost:8761/

info:
    app:
        name: lookup-services
        description: Searches for all micro services so the front end asks for the ports and locations
        version: 1.0
        Development State: Ready
        Main Features: Eureka Discovery Client
        Inicio API: http://localhost:5930/lookup/{service-name}
        Example: GET http://localhost:5930/lookup/CLIENT-ASIGNAR-JUEGOS
        Swagger: http://localhost:${SERVER_PORT:0}/swagger-ui.html
        TODO: Nothing