server:
    port: ${PORT:${SERVER_PORT:0}}

eureka:
    instance:
        hostname: localhost
        instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    client:
        service-url:
            default-zone: http://localhost:8761/

info:
    app:
        name: Validates Spanish DNI from players communicating with feign (also 10 digits passports)
        description: Validates Spanish DNI 9 digits number, by default desactivated for Development purposes., by default also accepts 10 digits numbers
        version: 1.0
        Development State: Ready
        Main Features: Spring Boot, Feign, Swagger2 to document the api
        Inicio API: http://localhost:${PORT:${SERVER_PORT:0}}/validator
        Example: POST http://localhost:${PORT:${SERVER_PORT:0}}/validator/dni/{dni}
        Swagger: http://localhost:${PORT:${SERVER_PORT:0}}/swagger-ui.html
        TODO: Checks 9 Digits Spanish DNI, but also allows 10 digits Passport because I don´t have DNI