server:
    port: ${PORT:${SERVER_PORT:0}}

eureka:
    instance:
        hostname: localhost
        instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    client:
        service-url:
            default-zone: http://localhost:8761/

info:
    app:
        name: Micro-service to retrieve corba news
        description: Connects to corba and read all the news from the server
        version: 1.0
        Development State: Ready
        Main Features: Eureka Discovery Client and dinamically stantiated by Angular
        Start API: http://localhost:PORT/corba/news
        WARNING: Make sure to first run start orbd -ORBInitialPort 1050 on Windows to Run Corba, then run "BufferServer.java" lcoated in "servicorcomponentecorba"