package com.dbc770.BufferApp;

/**
* BufferApp/BufferHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Buffer.idl
* domingo 22 de febrero de 2015 18H46' CET
*/

public final class BufferHolder implements org.omg.CORBA.portable.Streamable
{
  public Buffer value = null;

  public BufferHolder ()
  {
  }

  public BufferHolder (Buffer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BufferHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BufferHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BufferHelper.type ();
  }

}
